### ISSUE TITLE
Unable to install iron elements

### ISSUE THREAD

**Issue by paranoid-android** [PolymerElements/iron-elements#27]
Hello,

I am trying to create a basic app using Polymer. Along with that, I'm trying to include Iron and Paper elements. To begin, I ran the following from the command-line:

```
bower install PolymerElements/iron-elements
```

Oddly, if I run that command a second time, I receive the following error:

```
bower ENOENT        ENOENT: no such file or directory, lstat '/Users/user/MyApp/src/res/packages/iron-behaviors'

Stack trace:
statCb (/usr/local/lib/node_modules/bower/node_modules/fstream/lib/reader.js:145:25)
FSReqWrap.oncomplete (fs.js:82:15)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
System info:
Bower version: 1.6.5
Node version: 4.0.0
OS: Darwin 15.0.0 x64
```

I ran it twice in a row because when I went to install the paper elements via `bower install PolymerElements/paper-elements`, it threw errors related to the iron elements saying some were missing. 

How do I install iron-elements and paper-elements in the same project? There seems to be some kind of dependency or versioning bug. At this time. However, I cannot tell if the problem is with iron-elements or paper-elements.

**Comment by notwaldorf** [comment]
I've just successfully ran `bower install PolymerElements/iron-elements`, and it was fine. I think there's a problem with your local install of `bower`. Would you mind checking you have the latest update/reinstalling `bower` and trying again?
